### ISSUE TITLE
Cannot train new UDPipe2 model in Google Colab

### ISSUE THREAD

**Issue by Futyn-Maker** [ufal/udpipe#171]
Hi! Thanks for this amazing tool!

I'm a student, and I'm currently working on a project to study the quality of different models for a low-resource language with high spelling variability. I need to train and test the UDPipe2 model (there is data, there was no model before). The problem is that I get an error when trying to do this in Google Colab.

I know that UDPipe2 requires Python 3.7 and older versions of many libraries, including Tensorflow (according to requirements), so I installed Python 3.7 and made a virtual environment 
with the necessary dependencies.

I calculated the embeddings successfully, but when I try to train the model itself, I get the following error:

```
2023-05-22 00:05:45.959817: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[26,119] = [26, 121] does not index into param shape [32,121,512]
Traceback (most recent call last):
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return 
fn(*args)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[26,119] = [26, 121] does not index into param shape [32,121,512]
	 [[{{node GatherNd}}]]

During handling of the above exception, 
another exception occurred:

Traceback (most recent call last):
  File "/content/udpipe2/udpipe2.py", line 516, in <module>
    network.train_epoch(train, learning_rate, args)
  File "/content/udpipe2/udpipe2.py", line 331, in train_epoch
    self.session.run([self.training, self.training_summaries], feeds)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", 
line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/content/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[26,119] = [26, 121] does not index into param shape [32,121,512]
	 [[node GatherNd 
(defined at /venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'GatherNd':
  File "/udpipe2/udpipe2.py", line 498, in <module>
    network.construct(args, train, devs, tests, predict_only=args.predict)
  File "/udpipe2/udpipe2.py", line 208, in construct
    deprel_roots = tf.gather_nd(self.deprel_hidden_layer, deprel_indices, )
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return 
target(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 4277, in gather_nd
    return gen_array_ops.gather_nd(params, indices, name=name)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3976, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", 
line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

When training, I use standard hyperparameters, but I also tried to change them - it didn't help.
What can such a problem indicate, and how can it be solved?

My notebook with steps:
https://gist.github.com/Futyn-Maker/7d4debe13fe14d6f8c4b4d8d93a11708

**Comment by foxik** [comment]
Hi,

I tried training on your data (i.e., https://github.com/UniversalDependencies/UD_Old_East_Slavic-Ruthenian) and it worked in my setup. The dev metrics after 23 epochs (out of 60, so it would still improve) were
```
Dev  epoch 23, lr 0.001, UPOS: 97.36, XPOS: 96.95, UFeats: 91.25, AllTags: 90.02, Lemmas: 89.71, UAS: 83.85, LAS: 78.83, CLAS: 73.34, MLAS: 63.10, BLEX: 62.57
```

After some inspection, I think I know what is going on. The error you are seeing is a combination of 2 issues:
- during training, the following option
  ```python
  parser.add_argument("--max_sentence_len", default=120, type=int, help="Max sentence length.")
  ```
  is used to limit the length of the sentences to avoid OOM during training. This option limits the length of a sentence to 120 word by ignoring all other ones during loading. However, the HEADs are kept intact.

- in your notebook, you can see the GPU was not initialized properly:
  ```
  2023-05-22 00:05:25.393585: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.393713: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.393819: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.393923: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.394029: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.394154: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.394259: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
  2023-05-22 00:05:25.394275: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1662] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
  Skipping registering GPU devices...
  ```

Now during training, when predicting the heads, I index the computed hidden layer with word representations by the indices from HEADs. For the truncated sentences, these HEADs can point out of the maximum limit of 120 words. On GPU, this indexing operation works (even for out-of-bound indices, for which it returns zeros), but on CPU it crashes (this behavior is described at https://www.tensorflow.org/api_docs/python/tf/gather_nd in the Caution block).

So to deal with the problem:
- you need to make sure your GPU is initialized. The problem is that TF 1.15 requires old CUDA (according to https://www.tensorflow.org/install/source#gpu it is CUDA 10.0 and cuDNN 7.4).

  Alternatively, NVIDIA maintains a TF 1 fork that uses new CUDA (and Python 3.8), at https://github.com/NVIDIA/tensorflow, but it is not easy to install it if I remember correctly.

  Once the GPU is initialized, the error will go away.

- the indexing issue could be fixed properly by limiting the HEADs in the loaded files to the `args.max_sentence_len`; however, it manifests only on a CPU and the training would take very long without GPU, so I have little motivation to do it ;-)

Cheers!
